networks:
  frontend:
  backend:

services:
  app:
    env_file:
      - .env
    build:
      context: ./app
      dockerfile: Dockerfile
      secrets:
        - postgres-user
        - postgres-password
      args:
        POSTGRES_USER_FILE: /run/secrets/postgres-user
        POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
        POSTGRES_DB: myapp
        POSTGRES_PORT: "5432"
    restart: unless-stopped
    networks:
      - frontend
      - backend
    environment:
      NODE_ENV: production
    depends_on:
      - db
    secrets:
      - postgres-user
      - postgres-password
  db:
    image: postgres:16
    restart: unless-stopped
    networks:
      - backend
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres-user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
      POSTGRES_DB: myapp
    volumes:
      - postgres:/var/lib/postgresql/data
    secrets:
      - postgres-user
      - postgres-password
  caddy:
    image: caddy:2.7.5
    restart: unless-stopped
    depends_on:
      - app
    networks:
      - frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy:/data
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  postgres:
  caddy_data:
  caddy_config:

secrets:
  postgres-user: 
    file: ./secrets/postgres-user.txt
  postgres-password: 
    file: ./secrets/postgres-password.txt

