networks:
  frontend:
  backend:

services:
  db:
    image: postgres:16
    restart: unless-stopped
    networks:
      - backend
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres-user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
    volumes:
      - postgres:/var/lib/postgresql/data
    secrets:
      - postgres-user
      - postgres-password
  app:
    env_file:
      - .env
    build:
      context: ./app
      dockerfile: Dockerfile.dev
      secrets:
        - postgres-user
        - postgres-password
      args:
        POSTGRES_USER_FILE: /run/secrets/postgres-user
        POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_PORT: ${POSTGRES_PORT}
    restart: unless-stopped
    networks:
      - frontend
      - backend
    ports:
      - "127.0.0.1:5173:5173"
      - "127.0.0.1:24678:24678"
      - "127.0.0.1:5555:5555"
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      DEVELOPMENT: "true"
    depends_on:
      - db
    secrets:
      - postgres-user
      - postgres-password
  cron:
    env_file:
      - .env
    build: ./cron-service
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - backend

volumes:
  postgres:

secrets:
  postgres-user: 
    file: ./secrets/postgres-user.txt
  postgres-password: 
    file: ./secrets/postgres-password.txt
  internal-api:
    file: ./secrets/internal-api.txt
  neon-user:
    file: ./secrets/neon-user.txt
  neon-api-key:
    file: ./secrets/neon-api-key.txt
  gmail-user:
    file: ./secrets/gmail-user.txt
  gmail-pass:
    file: ./secrets/gmail-pass.txt
  flodesk-key:
    file: ./secrets/flodesk-key.txt

