networks:
  frontend:
  backend:

services:
  db:
    image: postgres:16
    restart: unless-stopped
    networks:
      - backend
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres-user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
      POSTGRES_DB: myapp
    secrets:
      - postgres-user
      - postgres-password
  redis:
    image: redis:7.2.3
    restart: unless-stopped
    networks:
      - backend
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
      secrets:
        - postgres-user
        - postgres-password
      args:
        POSTGRES_USER_FILE: /run/secrets/postgres-user
        POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
        POSTGRES_DB: myapp
        POSTGRES_PORT: "5432"
    restart: unless-stopped
    networks:
      - frontend
      - backend
    ports:
      - "127.0.0.1:5173:5173"
      - "127.0.0.1:24678:24678"
      - "127.0.0.1:5555:5555"
      - "127.0.0.1:9229:9229"
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres-user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
      POSTGRES_DB: myapp
      POSTGRES_PORT: "5432"
      REDIS_URL: redis://redis:6379
      DEVELOPMENT: "true"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    secrets:
      - postgres-user
      - postgres-password
    command: npm run dev -d -- --host 0.0.0.0

secrets:
  postgres-user: 
    file: ./secrets/postgres-user.txt
  postgres-password: 
    file: ./secrets/postgres-password.txt

