name: Build, Push, and Deploy Classes Page App

on:
  push:
    branches: [ "main" ]
    paths:
      - 'app/**'

env:
  AWS_REGION: us-east-2
  APP_ECR_REPO: classes-page

jobs:
  build-app:
    name: Build and Push Classes Page App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: ./app
          platforms: linux/amd64
          push: true
          cache-from: type=registry,ref=${{ steps.login-ecr.outputs.registry }}/${{ env.APP_ECR_REPO }}:buildcache
          cache-to: mode=max,image-manifest=true,oci-mediatypes=true,type=registry,ref=${{ steps.login-ecr.outputs.registry }}/${{ env.APP_ECR_REPO }}:buildcache
          secret-envs: |
            postgres-user=${{ secrets.POSTGRES_USER }}
            postgres-pass=${{ secrets.POSTGRES_PASS }}
            postgres-db=${{ secrets.POSTGRES_DB }}
            postgres-port=${{ secrets.POSTGRES_PORT }}
          tags: |
            ${{ steps.login-ecr.outputs.registry}}/${{ env.APP_ECR_REPO }}:latest
            ${{ steps.login-ecr.outputs.registry}}/${{ env.APP_ECR_REPO }}:${{ github.sha }}
