name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_TOKEN }}"
      - name: Build and Push
        uses: docker/build-push-action@v5.1.0
        with:
          context: "{{defaultContext}}:app"
          push: true
          secret-envs: |
            "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" 
            "POSTGRES_PASS=${{ secrets.POSTGRES_PASS }}"
            "POSTGRES_DB=${{ secrets.POSTGRES_DB }}"
            "POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}"
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/asmbly-classes:latest
            ${{ secrets.DOCKER_USERNAME }}/asmbly-classes:${{ github.sha }}
        
