name: Build, Push, and Deploy Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./app
          platforms: linux/amd64
          push: true
          secret-envs: |
            postgres-user=${{ secrets.POSTGRES_USER }}
            postgres-pass=${{ secrets.POSTGRES_PASS }}
            postgres-db=${{ secrets.POSTGRES_DB }}
            postgres-port=${{ secrets.POSTGRES_PORT }}
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/asmbly-classes-app:latest
            ${{ secrets.DOCKER_USERNAME }}/asmbly-classes-app:${{ github.sha }}
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy latest image
        uses: appleboy/ssh-action@master
        env:
          APPTOKEN: ${{ secrets.DOCKER_TOKEN }}
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          envs: APPTOKEN,USERNAME
          script: |
            echo $APPTOKEN | docker login -u $USERNAME --password-stdin
            export TAG="${{ github.sha }}"
            cd ~/app
            docker compose pull
            docker compose up --build -d
            
        
